### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_numpy() / Tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

### Function 1 - torch.from_numpy() / Tensor.numpy()

In [1]:
import torch
import numpy as np

a = np.random.rand(1,2,3,3)
print(a)
b = torch.from_numpy(a)
print(b)

[[[[0.01655801 0.69719037 0.36123405]
   [0.15745867 0.8293255  0.32668119]
   [0.87658851 0.13109675 0.7380236 ]]

  [[0.05475721 0.8986742  0.77391802]
   [0.84228414 0.50489304 0.1937051 ]
   [0.72206255 0.04306028 0.38218158]]]]
tensor([[[[0.0166, 0.6972, 0.3612],
          [0.1575, 0.8293, 0.3267],
          [0.8766, 0.1311, 0.7380]],

         [[0.0548, 0.8987, 0.7739],
          [0.8423, 0.5049, 0.1937],
          [0.7221, 0.0431, 0.3822]]]], dtype=torch.float64)


In [2]:
b.numpy()

array([[[[0.01655801, 0.69719037, 0.36123405],
         [0.15745867, 0.8293255 , 0.32668119],
         [0.87658851, 0.13109675, 0.7380236 ]],

        [[0.05475721, 0.8986742 , 0.77391802],
         [0.84228414, 0.50489304, 0.1937051 ],
         [0.72206255, 0.04306028, 0.38218158]]]])

### Function 2 - torch.unsqueeze() / torch.squeeze()

In [3]:
a = torch.tensor([[[1,2],[2,3]]], dtype=torch.float32)
print(f'Before unsqueeze: {a.size()}')

b = torch.unsqueeze(a, dim=0)
print(f'After unsqueeze: {b.size()}')

Before unsqueeze: torch.Size([1, 2, 2])
After unsqueeze: torch.Size([1, 1, 2, 2])


In [4]:
c = torch.squeeze(a, dim=0)
print(f'After squeeze: {c.size()}')

After squeeze: torch.Size([2, 2])


### Function 3 - tensor.transpose() / tensor.permute()

In [5]:
a = torch.tensor([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(f'Original shape: {a.size()}')

b = a.transpose(dim0=0, dim1=2)
print(f'Transpose shape: {b.size()}')

Original shape: torch.Size([2, 2, 3])
Transpose shape: torch.Size([3, 2, 2])


In [6]:
c = a.permute((1,2,0))
print(f'Permute shape: {c.size()}')

Permute shape: torch.Size([2, 3, 2])


### Function 4 - torch.reshape() / tensor.view()

In [7]:
a = torch.tensor([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(f'Original shape: {a.size()}')

b = torch.reshape(a, shape=(-1, 3))
print(f'Reshape shape: {b.size()}')

Original shape: torch.Size([2, 2, 3])
Reshape shape: torch.Size([4, 3])


In [8]:
c = a.view((-1,3))
print(f'View shape: {c.size()}')

View shape: torch.Size([4, 3])
